### ISSUE TITLE
Funcionalidad de menú: Ir al inicio debería mapear a la vista necesaria (listado de incidentes o incidente en curso)

### ISSUE THREAD

**Issue by fmoreyra** [tesis-cabal-cugno-moreyra/mobile-app#24]
En este momento, dicho botón no tiene ninguna funcionalidad relacionada.

**Comment by cabaljoaquin** [comment]
Cuando el usuario se logea o entra en la app, esta reconoce si se encuentra dentro de un incidente y lo redirecciona a la ventana correspondiente
